name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build test stack
        run: docker compose -f docker-compose.yml up --build -d
      - name: Lint & unit tests
        run: docker compose exec backend pytest
      - run: docker compose down
